### ISSUE TITLE
V2.0 Roadmap

### ISSUE THREAD

**Issue by XGHeaven** [ice-lab/icepkg#663]
Features:

- [ ] 支持并行编译
- [ ] 优化 transform/bundle 性能
- [ ] 升级 TypeScript/Rollup 等依赖版本，实验性接入 Rolldown
- [ ] 插件支持直接传入对象
- [ ] 将类型声明分离出来，作为独立的构建任务
  - [ ] 将 `declaration` 作为配置项，支持 `boolean | DeclarationUserConfig`，向前兼容 `true`、`false`。
  - [ ] 统一产出到 `typings` 目录下。
  - [ ] 支持配置生成引擎，包括但不限于 tsc、api-extractor、oxc-transform

Break Change:

- [ ] Bundle 模式
  - [ ] 默认开启 `browser`
  - [ ] 默认关闭 `polyfill`
  - [ ] 删除 `development`

Test:

- [ ] 提供完备的测试，优化 map 可能不一致的问题
